services:
  fftashio:
    build:
      context: .
      dockerfile: Dockerfile
    image: findingfocusdev/fftashio:latest
    container_name: fftashio
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000