services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fftashio
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000